# Generated by Django 2.1.15 on 2022-05-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='用户密码')),
                ('email', models.CharField(max_length=20, verbose_name='用户邮箱')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_status', models.IntegerField(default=0, verbose_name='用户状态')),
            ],
        ),
    ]
