# Generated by Django 2.1.15 on 2022-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('ticket_id', models.IntegerField(max_length=10, verbose_name='绑定的车票id')),
                ('user_id', models.IntegerField(max_length=10, verbose_name='绑定的用户id')),
                ('source', models.CharField(max_length=10, verbose_name='出发地')),
                ('target', models.CharField(max_length=10, verbose_name='目的地')),
                ('order_status', models.IntegerField(default=0, verbose_name='订单状态')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('source', models.CharField(max_length=10, verbose_name='出发地')),
                ('target', models.CharField(max_length=10, verbose_name='目的地')),
                ('num', models.IntegerField(max_length=20, verbose_name='余票数量')),
            ],
        ),
    ]
