# Generated by Django 2.2.12 on 2022-05-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='begin',
            field=models.CharField(max_length=10, null=True, verbose_name='出发时间'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='end',
            field=models.CharField(max_length=10, null=True, verbose_name='到达时间'),
        ),
    ]
