# Generated by Django 2.2.12 on 2022-05-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220518_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='begin',
            field=models.CharField(max_length=20, null=True, verbose_name='出发时间'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end',
            field=models.CharField(max_length=20, null=True, verbose_name='到达时间'),
        ),
    ]
